apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-component
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-component
  namespace: e2e-demo-dd5561a5-14aa-4bdf-bf34-cd54713b825a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodejs-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodejs-component
    spec:
      containers:
      - image: quay.io/psturc/test-images:7efb6f44ccf74e8883c9e070c9e06d2c
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources: {}
status: {}
